var htmlQuickMenu = '<strong>나의 신용정보</strong>';
htmlQuickMenu += '<div class="innerList">';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신용변동내역</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#" class="on">월간변동보고서</a></li>';
htmlQuickMenu += '<li><a href="#">신용명세서</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신용평점/등급</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#" class="on">신용평점/등급조회</a></li>';
htmlQuickMenu += '<li><a href="#">신용등급 예측하기</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신용개설내역</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">카드관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">보유카드내역</a></li>';
htmlQuickMenu += '<li><a href="#">카드이용실적</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">대출관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">대출거래내역</a></li>';
htmlQuickMenu += '<li><a href="#">채무조정내역</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">연체관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">단기연체내역</a></li>';
htmlQuickMenu += '<li><a href="#">채무불이행내역</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="">채무보증내역</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="">공공정보</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="">금융질서문란</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="">신용조회관리</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신상정보관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">NICE등록정보</a></li>';
htmlQuickMenu += '<li><a href="#">NICE등록정보 수정</a></li>';
htmlQuickMenu += '<li><a href="#">금융기관등록정보</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">A I 신용관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">크레딧어드바이저</a></li>';
htmlQuickMenu += '<li><a href="#">신용구매력지수</a></li>';
htmlQuickMenu += '<li><a href="#">대출거래지수</a></li>';
htmlQuickMenu += '<li><a href="#">NICE소득정보</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</div>';

//console.log(htmlQuickMenu);
$('#header .quickGnb').append(htmlQuickMenu);
