var htmlQuickMenu = '<nav class="quickGnb">';
htmlQuickMenu += '<strong>나의 신용정보</strong>';
htmlQuickMenu += '<div class="innerList">';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신용변동내역</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">월간변동보고서</a></li>';
htmlQuickMenu += '<li><a href="#">신용먕세서</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">신용평점/등급</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#" class="on">신용평점/등급조회</a></li>';
htmlQuickMenu += '<li><a href="http://www.daum.net">신용등급 예측하기</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="http://www.naver.com">신용개설내역</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">카드관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">보유카드내역</a></li>';
htmlQuickMenu += '<li><a href="#">카드이용실적</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">대출관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">대출거래내역</a></li>';
htmlQuickMenu += '<li><a href="#">채무조정내역</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</div>';
htmlQuickMenu += '</nav>';

//console.log(htmlQuickMenu);
$('#header .quickGnb').append(htmlQuickMenu);