var htmlQuickMenu = '<strong>나의 명의보호</strong>';
htmlQuickMenu += '<div class="innerList">';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">명의보호설정</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">명의보호내역</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">명의보호타임라인</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">스마트인증관리</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">스마트 인증내역 조회</a></li>';
htmlQuickMenu += '<li><a href="#">스마트 인증알람 관리</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">AI 명의보호</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">빅데이터 패턴분석</a></li>';
htmlQuickMenu += '<li><a href="#">위치기반 인증분석</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</div>';

//console.log(htmlQuickMenu);
$('#header .quickGnb').append(htmlQuickMenu);