var htmlQuickMenu = '<strong>가족 신용정보</strong>';
htmlQuickMenu += '<div class="innerList">';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">가족구성원관리</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">가족구성원등록</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">가족신용변동내역</a>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '<li>';
htmlQuickMenu += '<a href="#">가족신용정보</a>';
htmlQuickMenu += '<ul>';
htmlQuickMenu += '<li><a href="#">신용요약정보</a></li>';
htmlQuickMenu += '<li><a href="#">평점/등급내역</a></li>';
htmlQuickMenu += '<li><a href="#">여신거래내역</a></li>';
htmlQuickMenu += '<li><a href="#">카드사용내역</a></li>';
htmlQuickMenu += '<li><a href="#">연체내역</a></li>';
htmlQuickMenu += '<li><a href="#">금융조회내역</a></li>';
htmlQuickMenu += '<li><a href="#">금융신상정보</a></li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</li>';
htmlQuickMenu += '</ul>';
htmlQuickMenu += '</div>';

//console.log(htmlQuickMenu);
$('#header .quickGnb').append(htmlQuickMenu);